[GLOBAL]
pants_version = "2.18.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.plugin_development",
    "pants.backend.python.lint.autoflake",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.lint.docformatter",
    "pants.backend.python.lint.bandit",
    "pants.backend.python.typecheck.mypy",
    # if this is enabled, both black and isort break??
    #"pants.backend.python.lint.isort"
    "pants.backend.experimental.openapi",
    "experimental.datamodel_code_generator",
    #"sqlfluff",
]
pythonpath = ["src/python"]


[python]
interpreter_constraints = ["CPython==3.11.*"]
enable_resolves = true
